config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
   get 'users/:id', to: 'users/registrations#show', as: 'user'
  end
  # get "events/new", to: 'events#new'
  # post "events", to: 'events#create'
  # get "events", to: "events#index"
  # get '/events/:id', to: 'events#show', as: 'event'
  # resources :events

  resources :events do
    resources :attendee_events, only: [:create, :destroy]
  end


  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee_event.rb
class AttendeeEvent < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "user_id"
    has_many :attendee_events, dependent: :destroy
    has_many :attendees, through: :attendee_events

    scope :past, ->{where("time <= ?", Time.now)}
    scope :future, ->{where("time >= ?", Time.now)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: 'user_id', dependent: :destroy
  has_many :attendee_events, foreign_key: "attendee_id"
  has_many :attended_events, through: :attendee_events, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendee_events_controller.rb
class AttendeeEventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:create, :destroy]
  

    
  def create
        @attendee_event = @event.attendee_events.build
        @attendee_event.attendee = current_user
        if @attendee_event.save
            redirect_to @event, notice: 'Thanks for attending!'
        else
            render 'events/show'
        end
  end

  def destroy
    @attendee_event = AttendeeEvent.find_by(attendee_id: current_user.id, event_id: params[:id])
    @attendee_event.destroy
    redirect_to @event, notice: 'You have successfully removed your attendance.'
  end

  private
  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :require_permission, only: [:edit, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  

  

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create 
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: "Event was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_url(@event), notice: "Event was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
    end
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end
  
  def event_params
    params.require(:event).permit(:location, :time, :description)
  end

  def require_permission
    if current_user != Event.find(params[:id]).creator
      redirect_to root_path, alert: "You are not the creator of this event"
    end
  end
  
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  def show
    @user = User.find(params[:id])
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_events_helper.rb
module AttendeeEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
    <div class="card">
        <h4><%=event.creator.name%>'s event at : <%= event.location%></h4>
        <p><%=event.description%></p>
        <div class="special-actions">
            <p>Scheduled at: <%=event.time.in_time_zone(Time.zone).strftime("%d %B, %Y %H:%M")%></p>
            <p><%= event.attendees.count%> attending</p>
            <% if controller_name == 'events' && action_name == 'index' %>
              <%= render partial: 'links', locals: { event: event } %>
            <% end %>

        </div>
    </div>

app/views/events/_form.html.erb
<%= form_with(model: @event) do |form| %>
  <% if @event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_area :location %>
  </div>
    <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.datetime_local_field :time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/events/_links.html.erb
<%= link_to 'Details', event_path(event), class: "button btn-small" %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1>Events</h1>


  
<div class="cards-container">
  <h2>Past events:</h2>
  <div class="cards">
    <% @events.past.each do |event| %>
      <%= render event %>
    <% end %>
  </div>
</div>

<br>

<h2>Future events:</h2>
<div class="cards-container">
  <div class="cards">
      
      <% @events.future.each do |event| %>
    <%= render event %>
      <% end %>
  </div>
 
</div>

app/views/events/new.html.erb
<h1>Create new event</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<h2>Event details</h2>
<% @attendee_event ||= @event.attendee_events.build %>
<div class="cards">
  
  <%= render @event %>
  
  
      <div class="card">
        <h4>List of people attending</h4>
         <ul>
            <% @event.attendees.each do |attendee| %>
              <li><%= attendee.name %></li>
            <% end %>
          </ul>
      </div>
</div>
<div class="links">
    <%if AttendeeEvent.exists?(attendee_id: current_user.id, event_id: @event.id)%>
      <%= button_to 'Remove attendance', event_attendee_event_path(event_id: @event.id, attendee_id: current_user.id),class:"button", method: :delete %>
    <%else%>
      <%= form_with model: [@event, @attendee_event], local: true do |form| %>
      <%= form.submit "I will be there!", class: "button" %>
      <%end%>
  
    <%end%>


  <%= link_to "Edit", edit_event_path(@event), class:"button" %> 
  <%= button_to "Delete event", @event, class:"delete", method: :delete%>
  <%= link_to "Back", root_path, class:"button"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar"%>
    <div class="container">
      <p class= "notice"><%= notice %></p>
      <p class= "alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header> <ul>
    <li><%= link_to "Home", root_path%></li>
    <% if user_signed_in? %>
        <li><%= link_to "#{current_user.name}'s Profile", user_path(current_user) %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign in",new_user_session_path%></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <% end %>
    <li><%=link_to "New Event", new_event_path%></li>
    
    </ul>
 
 </header>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>